openapi: 3.0.0
info:
  title: Consulta de Endereço
  version: v2
  x-displayName: Introdução
  description: >
    # Introducão

    Seja bem-vindo a documentação da API de consulta de Endereços!

    Nossa API foi criada utilizando o padrão REST que possibilita a integração de seu sistema ao nosso, sendo assim você também pode extender ou recriar as funcionalidades existentes na nossa plataforma, tudo isso consumindo a API que está documentada abaixo.



    # Como usar a API?

    Logo a seguir você encontrará todos os recursos e metódos suportados pela API, sendo que essa página possibilita que você teste os recursos e métodos diretamente através dela.



    # Autenticação

    Você precisa de uma chave de API (API Key) para identificar a conta que está realizando solicitações para a API. 

    Para isso você deve colocar sua chave de API no campo que se encontra topo desta página para que os métodos funcionem corretamente.

    No seu código e integração temos suporte para autenticação de diversas formas sendo eles: 

    HTTP Header (Authorization) ou HTTP Query String (api_key) nos dois modos passando o valor da sua chave de api (API Key).

    <!-- ReDoc-Inject: <security-definitions> -->
paths:
  "/v2/addresses/{postalCode}":
    get:
      tags:
        - Addresses
      summary: Consulta de Endereço por CEP
      description: "### Informações adicionais\r

        \ \r

        Utilize esta requisição para consultar os dados de um
        **Endereço** através do CEP.\r

        Os dados do **Endereço** são consultados no Diretório Nacional
        de Endereço (DNE) dos Correios \r

        unificando com os dados de Cidades do IBGE."
      operationId: V2AddressesByPostalCodeGet
      parameters:
        - name: postalCode
          in: path
          description: Código do CEP
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Sucesso na requisição
          content:
            application/json:
              schema:
                type: object
                properties:
                  addresses:
                    type: array
                    items:
                      type: object
                      properties:
                        state:
                          type: string
                        city:
                          type: object
                          properties:
                            code:
                              type: string
                            name:
                              type: string
                        district:
                          type: string
                        additionalInformation:
                          type: string
                        streetSuffix:
                          type: string
                        street:
                          type: string
                        number:
                          type: string
                        numberMin:
                          type: string
                        numberMax:
                          type: string
                        postalCode:
                          type: string
                        country:
                          type: string
        "400":
          description: Algum parametro informado não é válido, verificar resposta
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          format: int32
                          type: integer
                        message:
                          type: string
        "401":
          description: Não autorizado, verificar o cabeçalho do HTTP Authorization
        "403":
          description: Accesso proibido
        "404":
          description: Nenhum endereço foi encontrado com o CEP informado
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          format: int32
                          type: integer
                        message:
                          type: string
        "500":
          description: Erro no processamento
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          format: int32
                          type: integer
                        message:
                          type: string
      security:
        - Authorization_Header:
            - apiKey
        - Authorization_QueryParam:
            - apiKey
  /v2/addresses:
    get:
      tags:
        - Addresses
      summary: Pesquisa de Endereço por campos
      description: Você precisará do APIKEY da Empresa
      operationId: V2AddressesGet
      parameters:
        - name: $filter
          in: query
          description: Termo genérico de pesquisa
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Sucesso na requisição
          content:
            application/json:
              schema:
                type: object
                properties:
                  addresses:
                    type: array
                    items:
                      type: object
                      properties:
                        state:
                          type: string
                        city:
                          type: object
                          properties:
                            code:
                              type: string
                            name:
                              type: string
                        district:
                          type: string
                        additionalInformation:
                          type: string
                        streetSuffix:
                          type: string
                        street:
                          type: string
                        number:
                          type: string
                        numberMin:
                          type: string
                        numberMax:
                          type: string
                        postalCode:
                          type: string
                        country:
                          type: string
        "400":
          description: Algum parametro informado não é válido
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          format: int32
                          type: integer
                        message:
                          type: string
        "401":
          description: Não autorizado, verificar o cabeçalho do HTTP Authorization
        "403":
          description: Accesso proibido
        "404":
          description: Termos não encontrados
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          format: int32
                          type: integer
                        message:
                          type: string
        "500":
          description: Erro no processamento
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          format: int32
                          type: integer
                        message:
                          type: string
      security:
        - Authorization_Header:
            - apiKey
        - Authorization_QueryParam:
            - apiKey
  "/v2/addresses/{term}":
    get:
      tags:
        - Addresses
      summary: Pesquisa de Endereço por termo genérico
      description: Você precisará do APIKEY da Empresa
      operationId: V2AddressesByTermGet
      parameters:
        - name: term
          in: path
          description: Termo genérico de pesquisa
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Sucesso na requisição
          content:
            application/json:
              schema:
                type: object
                properties:
                  addresses:
                    type: array
                    items:
                      type: object
                      properties:
                        state:
                          type: string
                        city:
                          type: object
                          properties:
                            code:
                              type: string
                            name:
                              type: string
                        district:
                          type: string
                        additionalInformation:
                          type: string
                        streetSuffix:
                          type: string
                        street:
                          type: string
                        number:
                          type: string
                        numberMin:
                          type: string
                        numberMax:
                          type: string
                        postalCode:
                          type: string
                        country:
                          type: string
        "400":
          description: Algum parametro informado não é válido
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          format: int32
                          type: integer
                        message:
                          type: string
        "401":
          description: Não autorizado, verificar o cabeçalho do HTTP Authorization
        "403":
          description: Accesso proibido
        "404":
          description: Nenhum endereço encontrado para o termo
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          format: int32
                          type: integer
                        message:
                          type: string
        "500":
          description: Erro no processamento
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          format: int32
                          type: integer
                        message:
                          type: string
      security:
        - Authorization_Header:
            - apiKey
        - Authorization_QueryParam:
            - apiKey
servers:
  - url: //address.api.nfe.io
components:
  securitySchemes:
    Authorization_Header:
      name: Authorization
      in: header
      type: apiKey
      description: Autenticar usando o Cabeçalho HTTP Authorization com sua API Key
    Authorization_QueryParam:
      name: apikey
      in: query
      type: apiKey
      description: 'Autenticar usando o Parametro na URL, exemplo:
        "/?apikey={APIKEY_TOKEN}"'
