<?php

declare(strict_types=1);

namespace Nfe\Build;

/**
 * Wraps a compiled class/enum body with the file header, namespace
 * declaration, and AUTO-GENERATED marker.
 */
final class Emitter
{
    /**
     * @param string $body          The compiled class or enum source (no `<?php`, no namespace).
     * @param string $namespace     PHP namespace this file belongs to (e.g., "Nfe\Generated\ServiceInvoiceRtcV1").
     * @param string $sourceSpec    Repo-relative path of the source YAML.
     * @param string $sourceHash    SHA-256 of the source YAML.
     */
    public static function emit(string $body, string $namespace, string $sourceSpec, string $sourceHash): string
    {
        $header = "<?php\n\n"
            . "// AUTO-GENERATED by scripts/generate.php — DO NOT EDIT.\n"
            . "// Source: {$sourceSpec}\n"
            . "// Hash:   sha256:{$sourceHash}\n\n"
            . "declare(strict_types=1);\n\n"
            . "namespace {$namespace};\n\n";

        return $header . rtrim($body) . "\n";
    }
}
